### PR TITLE
fixes image fit property not properly working

### PR DESCRIPTION
**Pull request by lscardinali**
Apparently the newly added FadeTransition Widget has trouble expanding its size to fill its parent widget. By putting a Container as a parent and setting the Width and Height to a MediaQuery fixes the problem, allowing the image to fully expand

References:
This StackOverflow post describes a bit what was happening and how to solve it
[https://stackoverflow.com/questions/54239068/correctly-fit-image-with-fadeinimage-flutter](url)

This Pull Request should solve the following issue:
[https://github.com/renefloor/flutter_cached_network_image/issues/134](url)

### CODE REVIEW

**Comment by lscardinali** [comment]
Changed a bit the implementation, using the container caused some problems in some other image dispositions. Also Pull Request #139 has problems making the image extend to all edges.
With the new code, the image should expand to the available width and height when those are not provided.

**Comment by renefloor** [comment]
@lscardinali not sure what you mean with `Also Pull Request #139 has problems making the image extend to all edges.`, but that pull request seems to work nicely with some cases I tested and seems to be a cleaner solution.

**Comment by lscardinali** [comment]
I'll run some more tests on pull request 139. The time i tried to add that fix to my app did work on most cases but there were one that was still broken. If i can't find any problems then i'll close this PR.
Thanks and sorry for not being clear on the description.

**Comment by renefloor** [comment]
No problem. Thanks for helping. I don't know all the possible cases myself.

**Comment by lscardinali** [comment]
Sorry, the problem was on my side. I'll close this PR now.

**Pull request closed without merging**
